# Navigation Links
# The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects & Products
    url: projects/
    weight: 30
  - name: Services
    url: services/
    weight: 40
  - name: Skills
    url: skills/
    weight: 50
  - name: Education
    url: education/
    weight: 60
  - name: Contact
    url: contact/
    weight: 70
  - name: Terms
    url: terms/
    weight: 80
  - name: Privacy
    url: privacy/
    weight: 90
